##CREATE SCHEMA IF NOT EXISTS `leaderboard` ;

##CREATE USER DETAIL TABLE
CREATE TABLE IF NOT EXISTS `leaderboard`.`user_detail` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NOT NULL,
  `AGE` INT NOT NULL DEFAULT 0,
  `POINTS` INT NOT NULL DEFAULT 0,
  `ADDRESS` LONGTEXT NULL,
  `CREATED_DATE` DATETIME NULL,
  `LAST_UPDATED_DATE` DATETIME NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  UNIQUE INDEX `USER_NAME_UNIQUE` (`NAME` ASC) VISIBLE);