##CREATE USER DETAIL TABLE
CCREATE TABLE `leadershipBoard`.`USER_DETAIL` (
  `ID` INT NOT NULL AUTO_INCREMENT DEFAULE 0,
  `NAME` VARCHAR(255) NOT NULL,
  `AGE` INT NOT NULL DEFAULT 0,
  `POINTS` INT NOT NULL DEFAULT 0,
  `ADDRESS` LONGTEXT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  UNIQUE INDEX `USER_NAME_UNIQUE` (`NAME` ASC) VISIBLE);
  
##Including Audit Columns  
ALTER TABLE `leadershipBoard`.`USER_DETAIL` 
ADD COLUMN `CREATED_DATE` DATETIME NULL AFTER `ADDRESS`,
ADD COLUMN `LAST_UPDATED_DATE` DATETIME NULL AFTER `CREATED_DATE`;